site_name: Véloroutes et voies vertes COVADIS
site_author: 3Liz
site_description: Extension QGIS pour les véloroutes et voies vertes COVADIS
site_url: https://docs.3liz.org/qgis-veloroutes_voies_vertes-plugin/
repo_url: https://github.com/3liz/qgis-veloroutes_voies_vertes-plugin
copyright: '<span class="copyleft">&copy;</span> 3Liz'

docs_dir: docs
site_dir: build

nav:
    - docs.3liz.org: '../'
    - Accueil: index.md
    - Guide utilisateur:
        - 'Installation': 'user-guide/installation.md'
    - Traitements: processing/README.md
    - Références: references.md
    - Changelog: changelog.md
    - Contribution: contributing.md
    - Base de données: database/index.html

markdown_extensions:
  # - git-revision-date:
  - toc:
      permalink: "#"
  - meta:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.superfences:
  - pymdownx.tabbed:
  - pymdownx.magiclink:
  - pymdownx.tasklist:
  - pymdownx.snippets:
  - pymdownx.keys:
  - attr_list:

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css

theme:
  name: material
  font: false
  icon:
    repo: fontawesome/brands/github-alt
  language: 'fr'
  logo: media/icon.png
  favicon: media/icon.png
  palette:
    accent: deep-orange
    primary: green
    scheme: preference
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/3LIZ_news

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/3liz

    - icon: fontawesome/brands/github
      link: https://github.com/3liz/

    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/3liz
